package com.hyrrx.forgottenrealmsrts.client.ui;

/**
 * Where each unit's front-facing parts sit on its skin sheet.
 *
 * <p>GENERATED by {@code tools/gen_unit_atlases.py java} from
 * {@code client/RtsUnitLayers.java}. Do not hand-edit: the HUD portrait blits these
 * rectangles straight out of the entity texture, so a number that disagrees with the
 * mesh draws the wrong pixels silently. Re-run the generator after changing a layer.</p>
 */
public final class RtsUnitPortraitRegions {
    /** One rectangle on the skin sheet, in texels. */
    public record Region(int u, int v, int width, int height) {
    }

    /**
     * A part drawn over another, with its offset from that part's top-left front corner
     * in model units. A visor sits across the eyes and a crown sits above the skull; the
     * offset is what keeps each of them where it belongs instead of top-aligned.
     */
    public record Overlay(Region region, int offsetX, int offsetY) {
    }

    /**
     * The rectangles the portrait needs. {@code headgear} and {@code torso} name the part
     * actually visible from the front, which is the helmet and cuirass rather than the
     * head and tunic they cover. Arms and legs are mirrored by the humanoid mesh, so one
     * rectangle serves both sides.
     */
    public record Portrait(int sheet, Region head, Overlay headgear, Overlay torso,
                           Region arm, Region leg) {
    }

    private RtsUnitPortraitRegions() {
    }

    /** createPeasantLayer — headgear hood_shell, torso body. */
    public static final Portrait PEASANT = new Portrait(
            128,
            new Region(8, 8, 8, 8),
            new Overlay(new Region(61, 41, 9, 4), 0, -2),
            new Overlay(new Region(20, 20, 8, 12), 0, 0),
            new Region(44, 20, 4, 12),
            new Region(4, 20, 4, 12));

    /** createSoldierLayer — headgear helmet, torso cuirass. */
    public static final Portrait SOLDIER = new Portrait(
            128,
            new Region(8, 8, 8, 8),
            new Overlay(new Region(43, 41, 9, 4), 0, -2),
            new Overlay(new Region(5, 37, 9, 11), 0, 0),
            new Region(44, 20, 4, 12),
            new Region(4, 20, 4, 12));

    /** createArcherLayer — headgear archer_hood, torso archer_cowl. */
    public static final Portrait ARCHER = new Portrait(
            128,
            new Region(8, 8, 8, 8),
            new Overlay(new Region(29, 41, 9, 4), 0, -1),
            new Overlay(new Region(69, 37, 8, 4), 0, 0),
            new Region(44, 20, 4, 12),
            new Region(4, 20, 4, 12));

    /** createSpearmanLayer — headgear spearman_cap, torso spearman_harness. */
    public static final Portrait SPEARMAN = new Portrait(
            128,
            new Region(8, 8, 8, 8),
            new Overlay(new Region(99, 37, 8, 2), 0, 0),
            new Overlay(new Region(9, 37, 9, 11), 0, 0),
            new Region(44, 20, 4, 12),
            new Region(4, 20, 4, 12));

    /** createCrossbowmanLayer — headgear crossbow_visor, torso brigandine. */
    public static final Portrait CROSSBOWMAN = new Portrait(
            128,
            new Region(8, 8, 8, 8),
            new Overlay(new Region(43, 50, 8, 2), 0, 5),
            new Overlay(new Region(5, 37, 9, 12), 0, 0),
            new Region(44, 20, 4, 12),
            new Region(4, 20, 4, 12));

    /** createFallenSoldierLayer — headgear ragged_crown, torso torn_cuirass. */
    public static final Portrait FALLEN_SOLDIER = new Portrait(
            128,
            new Region(8, 8, 8, 8),
            new Overlay(new Region(57, 41, 9, 2), 0, -1),
            new Overlay(new Region(5, 37, 9, 11), 0, 0),
            new Region(44, 20, 4, 12),
            new Region(4, 20, 4, 12));

    /** createSkeletalArcherLayer — headgear bone_crown, torso body. */
    public static final Portrait SKELETAL_ARCHER = new Portrait(
            128,
            new Region(8, 8, 8, 8),
            new Overlay(new Region(16, 40, 8, 2), 0, -1),
            new Overlay(new Region(20, 20, 8, 12), 0, 0),
            new Region(44, 20, 4, 12),
            new Region(4, 20, 4, 12));

    /** createSamuraiLayer — headgear face_guard, torso lamellar_cuirass. */
    public static final Portrait SAMURAI = new Portrait(
            128,
            new Region(8, 8, 8, 8),
            new Overlay(new Region(77, 50, 7, 2), 0, 5),
            new Overlay(new Region(5, 37, 9, 12), 0, 0),
            new Region(44, 20, 4, 12),
            new Region(4, 20, 4, 12));

    /** createFallenKnightLayer — headgear helm_visor, torso heavy_plate. */
    public static final Portrait FALLEN_KNIGHT = new Portrait(
            128,
            new Region(8, 8, 8, 8),
            new Overlay(new Region(97, 52, 8, 2), 0, 4),
            new Overlay(new Region(69, 37, 10, 12), -1, 0),
            new Region(44, 20, 4, 12),
            new Region(4, 20, 4, 12));

    /** createFallenBruteLayer — headgear brute_brow, torso brute_chest. */
    public static final Portrait FALLEN_BRUTE = new Portrait(
            128,
            new Region(8, 8, 8, 8),
            new Overlay(new Region(47, 41, 10, 4), -1, -1),
            new Overlay(new Region(7, 39, 12, 12), -2, 0),
            new Region(44, 20, 4, 12),
            new Region(4, 20, 4, 12));
}
